workspace = {}

[package]
name = "yippee"
version = "0.0.1"
authors = ["Wu Yu Wei"]
edition = "2021"
license = "Apache-2.0 OR MIT"
description = "A web browser"
readme = "README.md"
repository = "https://github.com/wusyong/yippee"
documentation = "https://docs.rs/yippee"
categories = ["Web programming"]

[package.metadata.docs.rs]
targets = [
  "x86_64-unknown-linux-gnu",
  "x86_64-pc-windows-msvc",
  "x86_64-apple-darwin",
]

[features]
default = []


[build-dependencies]
cfg_aliases = "0.1"

[dependencies]
log = "0.4"
thiserror = "1.0"
raw-window-handle = { version = "0.5", features = ["std"] }
# Servo
libservo = { git = "https://github.com/servo/servo.git", rev = "e7d2d23", features = ["max_log_level", "native-bluetooth", "webdriver"] }
servo-media = { git = "https://github.com/servo/media" }
crossbeam-channel = "0.5"
getopts = "0.2.17"
surfman = { version = "0.8", features = ["chains", "sm-angle", "sm-angle-default", "sm-x11", "sm-raw-window-handle"] }
winit = { version = "0.29", features = ["rwh_05"] }

[target."cfg(any(target_os = \"ios\", target_os = \"macos\"))".dependencies]
block = "0.1"
cocoa = "0.25"
core-graphics = "0.23"
objc = "0.2"
objc_id = "0.1"

[patch.crates-io]
bindgen = { git = "https://github.com/sagudev/rust-bindgen", branch = "f16" }

# This is required because we want all dependencies that use WebRender to
# use our vendored version.
[patch."https://github.com/servo/webrender"]
webrender = { git = "https://github.com/servo/servo.git" }
webrender_api = { git = "https://github.com/servo/servo.git" }

[patch."https://github.com/servo/mozjs"]
mozjs = { git = "https://github.com/wusyong/mozjs", branch = "mozjs_mirror" }
